#!/usr/bin/perl

use strict;
use warnings;
use DBI;

$|=1;


sub randompass()
{
	my @alphanumeric = ('a'..'z', 'A'..'Z', 0..9,'!','_','-');
	my @numeric = (0..9);
	my $randpassword = '';

	while ( length($randpassword) < 8 ) {
              $randpassword = $randpassword . join '', map $alphanumeric[rand @alphanumeric], 0..(rand @numeric);
	}
	$randpassword .= '#';
	return $randpassword;
}

# We will just rebuild experiment name and 
# start SSH tunnel and novnc proxy
my $SSH = "ssh -o StrictHostKeyChecking=no";
    
# Take paper ID, type of VM to stop and user ID
# and set up SSH tunnel and novnc proxy

my $usage="$0 paper-ID vm-type user-ID\n";
my %opt = ();


if ($#ARGV < 2)
{
    print $usage;
    print "DONE";
    exit 1;
}

# Read info from conf/options.php
# to get orgName, dbUser, etc.
my $fh = new IO::File("conf/options.php");
while (<$fh>)
{
    if ($_ =~ /\$Opt/ && $_ =~ /\=/)
    {
	my @arr = split /[\[\]\"\=\s+\;]/, $_;	
	if ($#arr > 3)
	{
	    my $intake = 0;
	    for my $a (@arr)
	    {
		if ($a !~ /[\[\]\"\=\s+]/ && $a =~ /[a-zA-Z0-9]/)
		{
		    if ($a =~ /^\$Opt/)
		    {
			$intake = 1;
			next;
		    }
		    if ($intake =~ /^[0-9]$/ && $intake == 1)
		    {
			$opt{$a} = 0;
			$intake = $a;
		    }
		    else
		    {
			$opt{$intake} = $a;
			last;
		    }
		}
	    }
	}
    }
}
close($fh);


my $dsn = "DBI:mysql:database=$opt{'dbName'}";
my $dbh = DBI->connect($dsn, $opt{'dbUser'}, $opt{'dbPassword'});
my $sth;
my $paperID = $ARGV[0];
my $vmtype = $ARGV[1];
my $userID = $ARGV[2];
# Set server
my $cmd="mrg config set server grpc.mod.deterlab.net";
system($cmd);
my $proj = $opt{'clusterOrg'} . "p" . $paperID;
my $vmid = $vmtype . "." . $proj;
# Calculate which terminal ID should user have
$sth = $dbh->prepare(
	'SELECT contactID FROM VMaccess where vmid = ? order by contactID asc ')
	or die "prepare statement failed: $dbh->errstr()";
$sth->execute($vmid) or die "execution failed: $dbh->errstr()";
my $i=0;
my $found=0;
while (my $ref = $sth->fetchrow_hashref()) {
    my $ID = $ref->{'contactID'};
    print "My id $userID current $ID i $i\n";
    if ($ID == $userID)
    {
	$found = 1;
	last;
    }
    $i++;
}
if ($found == 0)
{
    print "This user has no access to the given VM\n";
    print "DONE";
    exit 1;
}
my $termID = $i;
my $vncport = $termID + 5900;
my $port = 10000 + $userID + 50*$paperID;
my $proxyport = 6080 + $userID + 50*$paperID;

print "Port $port proxyport $proxyport\n";

my $path=$opt{'webpath'};
my $config = "$path/config";
my $admin=$opt{'clusterUser'};
my $logincmd =  "mrg login " . $opt{'clusterUser'} . " -p \"" . $opt{'clusterPass'} . "\"";
$cmd = $logincmd;
system($cmd);
$cmd = "cp $path/.ssh/merge_key /tmp/ 2>&1";
my $output=`$cmd`;
$cmd = "chmod a+r /tmp/merge_key 2>&1";
$output=`$cmd`;
open(my $oh, '>', $config); # or die $!;
print $oh "
Host *
     IdentityFile $path/.ssh/merge_key
     ServerAliveInterval 30
     User $admin
     StrictHostKeyChecking no
     ProxyCommand ssh -o StrictHostKeyChecking=no -p 2022 -i $path/.ssh/merge_key -W %h:%p $admin\@jump.mod.deterlab.net";
close($oh);
# Create similar config for merge user
my $mconfig = "/tmp/config";
open($oh, '>', $mconfig); # or die $!;
print $oh "                                                                                                                                                                                                                           
Host *	
    IdentityFile /tmp/merge_key
    ServerAliveInterval 30
    User $admin
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null
    ProxyCommand ssh -o StrictHostKeyChecking=no -p 2022 -i /tmp/merge_key -W %h:%p $admin\@jump.mod.deterlab.net";
close($oh);
$logincmd =  "mrg login " . $opt{'clusterUser'} . " -p \"" . $opt{'clusterPass'} . "\" && ";
$output = `ps axuw | grep ssh | grep "localhost:$port " | wc | awk '{print \$1}'`;
if ($output <= 1)
{
    # Delete known_hosts on XDC just in case
    my $xdccmd = "rm /home/" . $opt{'clusterUser'} . ".ssh/known_hosts";
    $cmd = $logincmd . "sudo -H -u merge ssh -F $mconfig xdc-$proj \"$xdccmd\"";
    my $result=system($cmd);
    print "Creating new SSH tunnel";
    $cmd = $logincmd . "sudo -H -u merge ssh -F $mconfig -L " . $port . ":localhost:" . $port . " xdc-$proj -t ssh -L " . $port . ":localhost:" . $vncport . " -N node 2>&1 &";
    $result=system($cmd);
    if ($result != 0)
    {
	print "SSH tunnel creation failed\n";
	print "DONE";
	exit 1;
    }
}
$output = `ps axuw | grep novnc_proxy | grep "localhost:$port " | wc | awk '{print \$1}'`;
if ($output <= 1)
{
    print "Starting novnc proxy";
    $cmd = "/var/noVNC/utils/novnc_proxy --vnc localhost:" . $port . " --listen $proxyport 2>&1 &";
    my $result=system($cmd);
    if ($result != 0)
    {
	print "novnc_proxy failed\n";
	print "DONE";
	exit 1;
    }
}
print "User $userID term ID $termID\n";
print "DONE";
