#!/usr/bin/perl

use strict;
use warnings;
use DBI;

$|=1;


sub randompass()
{
	my @alphanumeric = ('a'..'z', 'A'..'Z', 0..9,'!','_','-');
	my @numeric = (0..9);
	my $randpassword = '';

	while ( length($randpassword) < 8 ) {
              $randpassword = $randpassword . join '', map $alphanumeric[rand @alphanumeric], 0..(rand @numeric);
	}
	print "Rand pass $randpassword\n";
	$randpassword .= '#';
	return $randpassword;
}

# Take paper ID, type of VM to create
# and a list of IDs that need access
# like startvm 2 small 4 2 1

my $usage="$0 paper-ID vm-type vnc-pass contact-IDs\n";
my %opt = ();


if ($#ARGV < 3)
{
    print $usage;
    print "DONE";
    exit 1;
}

# Read info from conf/options.php
# to get orgName, dbUser, etc.
my $fh = new IO::File("conf/options.php");
while (<$fh>)
{
    if ($_ =~ /\$Opt/ && $_ =~ /\=/)
    {
	my @arr = split /[\[\]\"\=\s+\;]/, $_;	
	if ($#arr > 3)
	{
	    my $intake = 0;
	    for my $a (@arr)
	    {
		if ($a !~ /[\[\]\"\=\s+]/ && $a =~ /[a-zA-Z0-9]/)
		{
		    if ($a =~ /^\$Opt/)
		    {
			$intake = 1;
			next;
		    }
		    if ($intake =~ /^[0-9]$/ && $intake == 1)
		    {
			$opt{$a} = 0;
			$intake = $a;
		    }
		    else
		    {
			$opt{$intake} = $a;
			last;
		    }
		}
	    }
	}
    }
}
close($fh);

my %vms=();
# Read VM descriptions from file
$fh = new IO::File($opt{'clusterVMs'});
while (<$fh>)
{
    my @items= split /\|/, $_;
    $items[1] =~ s/\n//;
    $vms{$items[0]} = $items[1];
}
close($fh);


my $dsn = "DBI:mysql:database=$opt{'dbName'}";
my $dbh = DBI->connect($dsn, $opt{'dbUser'}, $opt{'dbPassword'});
my $sth;
my %tocreate=();
my $paperID = $ARGV[0];
my $vmtype = $ARGV[1];
my $vncpass = $ARGV[2];
my $SSH = "ssh -o StrictHostKeyChecking=no";

# Set server
my $cmd="mrg config set server grpc.mod.deterlab.net";
system($cmd);
# Log in and copy key to user merge
my $path=$opt{'webpath'};
my $logincmd =  "mrg login " . $opt{'clusterUser'} . " -p \"" . $opt{'clusterPass'} . "\"";
$cmd = $logincmd;
system($cmd);
$cmd = "cp $path/data/.ssh/merge_key /tmp/ 2>&1";
my $output=`$cmd`;
$output=`$cmd`;
# Create a project for paper if it does not exist
my $proj = $opt{'clusterOrg'} . "p" . $paperID;
$cmd = $logincmd . " && mrg show project $proj";
print "Checking if project $proj exists\n";
my $result = system($cmd);
if ($result != 0)
{
    $cmd = $logincmd . " && mrg new project $proj \"" . $opt{'clusterOrg'} . " AE for paper " . $paperID . "\" --category Research -o " . $opt{'clusterOrg'};
    print "Creating new project $proj\n";
    $result = system($cmd);
}
# Figure out which cluster accounts we have created before
my $org = $opt{'clusterOrg'};
for (my $i = 3; $i <= $#ARGV; $i++)
{
    my $id = $ARGV[$i];
    my $username = $org . "u" .  $ARGV[$i];
    $sth = $dbh->prepare(
	'SELECT * FROM ClusterUsers WHERE contactID = ?')
	or die "prepare statement failed: $dbh->errstr()";
    $sth->execute($ARGV[$i]) or die "execution failed: $dbh->errstr()";
    # If no account exists according to HotCRP try to create it or re-create it and save
    if ($sth->rows == 0)
    {
	print "Create account for " . $ARGV[$i] . "\n";
	$sth = $dbh->prepare(
	    'SELECT * FROM ContactInfo WHERE contactID = ?')
	    or die "prepare statement failed: $dbh->errstr()";
	$sth->execute($ARGV[$i]) or die "execution failed: $dbh->errstr()";
	while (my $ref = $sth->fetchrow_hashref()) {
	    my $usstate = "";
	    my $firstName = $ref->{'firstName'};
	    my $lastName = $ref->{'lastName'};
	    my $email = $ref->{'email'};
	    my $affiliation = $ref->{'affiliation'};
	    my $country= $ref->{'country'};
	    if ($affiliation eq "")
	    {
		$affiliation = "HotCRP";
	    }
	    if ($country eq "" || $country eq "United States of America")
	    {
		$country = "United States";
	    }
	    if ($country eq "United States")
	    {
		$usstate = "--usstate CA";
	    }
	    my $password = randompass();
	    # Check if the user already exists, and if it does unregister them since we need to generate a new password
	    my $cmd = $logincmd . " && mrg show user $username";
	    print "Checking if user $username exists\n";
	    my $result = system($cmd);
	    if ($result == 0)
	    {
		# Assume that this will work
		$cmd = $logincmd . " && mrg delete user $username && mrg unregister $username";
		system($cmd);
		print "Existing user $username has been deleted, and new user will be created";
	    }
	    $cmd = "mrg register $username $email \"$firstName $lastName\" \"$affiliation\" Researcher \"$country\" $usstate -p \"$password\" -o $org";
	    print "Registering new user\n";
	    # Execute the command in new process
	    $result = system($cmd);
	    if ($result == 0)
	    {
		$cmd =  $logincmd . " && mrg membership confirm organization user " . $opt{'clusterOrg'} . " " . $username;
		$result = system($cmd);
		if ($result == 0)
		{
		    print "Successfully registered user $username\n";
		    my $sth1 = $dbh->prepare(
			'INSERT INTO ClusterUsers(contactID, username, password) values (?, ?, ?)')
			or die "prepare statement failed: $dbh->errstr()";
		    $sth1->bind_param(1, $id);
		    $sth1->bind_param(2, $username);
		    $sth1->bind_param(3,$password);
		    $sth1->execute or die "execution failed: $dbh->errstr()";
		    $sth1->finish;
		    # Join user to the project
		    $cmd = $logincmd . " && mrg update member project $proj $username";
		    $result = system($cmd);
		    if ($result != 0)
		    {
			print "Membership update for project $proj and user $username failed";
		    }
		}
		else
		{
		    print "Registration of $username for email $email has worked but we could not activate the user. Please contact testbed ops.\n";
		}
	    }
	    else
	    {
		print "Registration of $username for email $email has failed. Please contact testbed ops.\n";
	    }
	}
	$sth->finish;
    }
    else
    {
	# Join user to the project
	$cmd = $logincmd . " && mrg update member project $proj $username";
	$result = system($cmd);
	if ($result != 0)
	{
	    print "Membership update for project $proj and user $username failed";
	}
    }
    $sth->finish;
}
# Now create an XDC in that project if needed
# First create a config file
my $config = "$path/data/config";
my $admin=$opt{'clusterUser'};
open(my $oh, '>', $config) or die $!;
print $oh "
Host *
     IdentityFile $path/.ssh/merge_key
     ServerAliveInterval 30
     User $admin
     StrictHostKeyChecking no
     ProxyCommand ssh -o StrictHostKeyChecking=no -p 2022 -i $path/.ssh/merge_key -W %h:%p $admin\@jump.mod.deterlab.net";
close($oh);
# Create similar config for merge user
my $mconfig = "/tmp/config";
my $oh;
open($oh, '>', $mconfig) or die $!;
print $oh "                                                                                                                                                                                                                           
Host *	
    IdentityFile /tmp/merge_key
    ServerAliveInterval 30
    User $admin
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null
    ProxyCommand ssh -o StrictHostKeyChecking=no -p 2022 -i /tmp/merge_key -W %h:%p $admin\@jump.mod.deterlab.net";
close($oh);
$cmd=$logincmd . " && mrg list xdcs | grep xdc.$proj";
$result=system($cmd);
if ($result != 0)    
{    
    # XDC needs to be created
    print "Creating XDC xdc.$proj\n";
    $cmd=$logincmd . " && mrg new xdc xdc.$proj";
    $result=system($cmd);
    
    if ($result == 0)
    {
	sleep(30);
	# Created XDC, now need to wait for it to be live
	my $retries = 30;
	for (my $tries = 0; $tries < $retries; $tries++)
	{
	    print "Checking if the XDC is up\n";
	    $cmd = $logincmd . " && sudo -H -u merge $SSH -F $mconfig xdc-$proj \"ls ~\" 2>&1 < /dev/null ";
	    $result=system($cmd);
	    if ($result != 0)
	    {
		print "Result $result\n";
		sleep(1);		
	    }
	    else
	    {
		print "XDC is now operational\n";
		last;
	    }
	}
	if ($result != 0)
	{
	    print "XDC did not come up within prescribed time\n";
	    print "DONE";
	    exit 1;
	}
    }
    else
    {
	print "XDC creation has failed\n";
	print "DONE";
	exit 1;
    }
}



if ($result == 0)
{
    print "XDC exists and is running, we will now create the VM\n";
    # Now create the VM in that project
    my $xdccmd="/share/staging/startexp -p $proj -n $vmtype -m /share/EAC/$vmtype/$vmtype.model $vmtype";
    print "XDC command $xdccmd\n";
    $cmd = $logincmd . " && sudo -H -u merge $SSH -F $mconfig xdc-$proj \"$xdccmd\"";

    $result=system($cmd);
    if ($result == 0)
    {
	print "Experiment is now running\n";
	# Insert info into DB
	
	my $sth = $dbh->prepare(
	    'SELECT * FROM VMs WHERE vmid = ?')
	    or die "prepare statement failed: $dbh->errstr()";
	$sth->execute("$vmtype.$proj") or die "execution failed: $dbh->errstr()";
	# If VM doesn't exist, insert info
	if ($sth->rows == 0)
	{	    
	    $sth = $dbh->prepare(
	    'INSERT INTO VMs(vmid, vmtype, VNCpass, vmdesc, paperId) values (?, ?, ?, ?, ?)')
		or die "prepare statement failed: $dbh->errstr()";
	    $sth->bind_param(1, "$vmtype.$proj");
	    $sth->bind_param(2, $vmtype);
	    $sth->bind_param(3, $vncpass);	
	    $sth->bind_param(4, $vms{$vmtype});
	    $sth->bind_param(5, $paperID);
	    $sth->execute or die "execution failed: $dbh->errstr()";
	    $sth->finish;
	}
	for (my $i = 3; $i <= $#ARGV; $i++)
	{
	    my $id = $ARGV[$i];

	    # Check if we need to insert into access                                                                                           
	    my $sth = $dbh->prepare(
		'SELECT * FROM VMaccess WHERE vmid = ? AND contactID = ?')
		or die "prepare statement failed: $dbh->errstr()";
	    $sth->bind_param(1, "$vmtype.$proj");
	    $sth->bind_param(2, $id);
	    $sth->execute or die "execution failed: $dbh->errstr()";
	    $sth->finish;
	    
	    if ($sth->rows == 0)
	    {
		
		$sth = $dbh->prepare(
		    'INSERT INTO VMaccess (vmid, contactId) values (?, ?)')
		    or die "prepare statement failed: $dbh->errstr()";
		$sth->bind_param(1, "$vmtype.$proj");
		$sth->bind_param(2, $id);
		$sth->execute or die "execution failed: $dbh->errstr()";
		$sth->finish;
	    }
	}
    }
    else
    {
	print "Experiment failed to start\n";
	print "DONE\n";
	exit 1;
    }
}
# Now we should wait for the node to come up and initialize it
my $retries = 30;
my $running = 0;
for (my $tries = 0; $tries < $retries; $tries++)
{
    print "Checking if node is reachable\n";
    my $xdccmd="ping -c 1 node";
    $cmd = $logincmd . " && sudo -H -u merge $SSH -F $mconfig xdc-$proj \"$xdccmd\"";
    open(my $cmdh, " $cmd | ");
    my $output = "";
    while (<$cmdh>)
    {
	$output .= $_;
    }
    if ($output ne "")
    {
	print "Experiment is running and reachable\n";
	$running = 1;
	last;
    }
}
# Now run runlab
if ($running)
{
    print "Setting up experiment\n";
    $cmd = $logincmd . " && sudo -H -u merge $SSH -F $mconfig xdc-$proj \"/share/staging/runlab -f /share/EAC -v $vncpass $vmtype\" 2>&1 < /dev/null ";
    $result=system($cmd);
    if ($result != 0)
    {
	print "Something failed in experiment setup\n";
	print "DONE\n";
	exit 1;
    }
    else
    {
	print "Experiment has been set up\n";
	print "DONE";
	exit 0;
    }
}

