FROM docker.io/bitnami/php-fpm:latest

# this overwrites the settings in www.conf ...
RUN rm -f /opt/bitnami/php/etc/common.conf
COPY docker/files/www.conf /opt/bitnami/php/etc/php-fpm.d/www.conf

# enable access logging for debugging
RUN mkdir -p /opt/bitnami/php/log
RUN touch /opt/bitnami/php/log/www.access.log

COPY --chown=33:33 . /var/www/hotcrp
